name:                simple-dosbox-launcher
version:             0.1.1.0
synopsis:            A simple launcher for dosbox programs in zip files
description:         It can be used by distributions to package DOS programs.
homepage:            https://github.com/small-utils/simple-dosbox-launcher
license:             MPL-2.0
author:              crocket <748856+crocket@users.noreply.github.com>
copyright:           2018 crocket <748856+crocket@users.noreply.github.com>
maintainer:          748856+crocket@users.noreply.github.com
category:            Distribution
extra-source-files:
- README.adoc

dependencies:
  - base >= 4.7 && < 5
  - filepath
  - directory
  - optparse-applicative
  - typed-process
  - unix-compat

executables:
  simple-dosbox-launcher:
    source-dirs:      src
    main:             Main.hs
